version: '3.7'

services:
  database:
    container_name: sim_db
    image: postgres:15.3-alpine

    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

    ports:
      - "5432:5432"

  pgadmin:
    container_name: sim_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 1budsmoker1@gmail.com
      PGADMIN_DEFAULT_PASSWORD: kotik
    ports:
      - "5050:80"

volumes:
  database: