"""Initial migration.

Revision ID: f916d7663b26
Revises: 
Create Date: 2023-11-06 14:18:08.023988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Integer

from app.models import Roles
import sqlalchemy_utils.types.choice

# revision identifiers, used by Alembic.
revision = 'f916d7663b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(choices=Roles, impl=Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
